### ISSUE TITLE
StringSet support

### ISSUE THREAD

**Issue by hotchemi** [rejasupotaro/kvs-schema#4]
It doesn't seem to support `getStringSet` and `setStringSet`. Any reason?

**Comment by rejasupotaro** [comment]
There is no reason. I will implement it if you want.

**Comment by hotchemi** [comment]
Make sense. I'm very glad if u do that but it's not an urgent matter :eyes:

**Comment by hotchemi** [comment]
Awesome! This issue is no longer needed.

**Comment by rejasupotaro** [comment]
It was published. Thank you :smile:
