### ISSUE TITLE
Option which uses default preference

### ISSUE THREAD

**Issue by hotchemi** [rejasupotaro/kvs-schema#7]
@rejasupotaro 

One suggestion :octocat: 

### What

Implementing a option which use default preference(with `PreferenceManager. getDefaultSharedPreferences`).
I'm not sure the best interface but my candidates are creating new annotation like `@DefaultTable` or defining one string constant like `Table(Table.DEFAULT)` or `Table(Table.Type.DEFAULT)`.

### Why

It's so helpful to migration for existing app because a ton of app already use default preference I guess.

**Comment by hotchemi** [comment]
If it is fit to the library, I'm gonna implement this feature.

**Comment by rejasupotaro** [comment]
It's understandable, but

- I'd like to keep this library simple.
- SharedPreferences should be named, and be separated by its domain for maintainability.
- Developer should know about your shared preferences when developer try to migrate.

As for people who want to migrate existing SharedPreferences, I have an alternative for your suggestion. How about creating SharedPreferencesInfo class to display information about shared preferences like below?

```java
SharedPreferencesInfo.dump(context);

╔════════════════════════╗
║ example.prefs          ║
╠═══════════╪════════════╣
║ user_id   │ int        ║
╠═══════════╪════════════╣
║ user_name │ string     ║
╟───────────┼────────────╢
║ languages │ string_set ║
╚═══════════╧════════════╝
```

**Comment by hotchemi** [comment]
That's make sense. And `SharedPrefsInfo` seems interesting. Completely agree.

**Comment by rejasupotaro** [comment]
OK, I will work on it. Thank you :smile:

**Comment by hotchemi** [comment]
:innocent:
